// data.js — Corpus des dictées (FLE/FLS — Nouvelles Dictées)
// Thèmes : Maison, Chambre, Salon, Habitation, Quartier

const DICTEES = {
  Maison: [
    "J'habite une maison.",
    "Dans ma maison on compte quatre pièces principales.",
    "L'une d'elles est la salle à manger.",
    "Une autre est une chambre à coucher.",
    "En réalité, il y a deux chambres à coucher.",
    "Il y a aussi un salon et une cuisine.",
    "Les pièces de service ne sont pas comptées dans les pièces principales.",
    "La cuisine, l'office, etcaetera, sont des pièces de service.",
    "La salle de bains est séparée des W.C.",
    "Dans la salle à manger, nous prenons nos repas.",
    "Nous dormons dans les chambres à coucher.",
    "Parfois nous y faisons aussi la sieste.",
    "Nous utilisons notre salon pour lire, écouter de la musique ou recevoir des invités.",
    "Dans notre salle de bains, il y a une baignoire et une douche, un lavabo et un bidet.",
    "Dans notre salle à manger, il y a une table, six chaises et un buffet.",
    "Il y a aussi une pendule qui indique l'heure.",
    "Sur le buffet, il y a un vase qui contient souvent des fleurs.",
    "Les fleurs changent suivant les saisons.",
    "Dans le buffet se trouvent les couverts et les couteaux.",
    "Le service de table est en porcelaine.",
    "Il comprend une soupière, un saladier, des plats petits ou grands, longs ou ronds, des assiettes, petites ou grandes, creuses ou plates.",
    "Le service des verres comprend des verres de différentes dimensions, destinés aux divers vins."
  ],
  Chambre: [
    "Ma chambre à coucher est une pièce tranquille.",
    "Dans ma chambre, il y a un lit, une armoire et une commode.",
    "Mon lit est recouvert d'un couvre-lit.",
    "Sur la commode, il y a un miroir.",
    "Je range mes vêtements dans l'armoire.",
    "La fenêtre de ma chambre donne sur le jardin.",
    "Le matin, j'ouvre les rideaux pour laisser entrer la lumière.",
    "Le soir, je ferme les volets pour dormir dans l'obscurité.",
    "Ma chambre est bien chauffée en hiver.",
    "En été, j'ouvre la fenêtre pour aérer la pièce.",
    "Sur ma table de nuit, il y a une lampe et un livre.",
    "Je lis souvent avant de m'endormir.",
    "Mon réveil sonne chaque matin à sept heures.",
    "Je fais mon lit chaque matin avant de partir.",
    "Le plancher de ma chambre est recouvert d'un tapis.",
    "Les murs sont peints en blanc et bleu.",
    "Il y a des tableaux accrochés aux murs.",
    "Dans un coin de la chambre, il y a un petit bureau.",
    "Je travaille parfois à ce bureau le soir.",
    "Une bibliothèque occupe tout un pan de mur.",
    "Mes livres préférés y sont rangés par ordre alphabétique.",
    "Le plafond de ma chambre est haut.",
    "Un joli lustre éclaire toute la pièce.",
    "La chambre est ma pièce préférée de la maison.",
    "J'y passe beaucoup de temps à lire et à me reposer.",
    "Parfois j'écoute de la musique dans ma chambre.",
    "Je range mes chaussures sous le lit ou dans l'armoire.",
    "Ma chambre est toujours bien rangée.",
    "Je change les draps chaque semaine.",
    "Ma mère m'aide parfois à faire le grand ménage.",
    "Nous lavons les rideaux deux fois par an.",
    "La chambre sent bon quand les fleurs du jardin sont en fleur.",
    "Je garde une petite plante verte sur le rebord de la fenêtre.",
    "Ma chambre est mon espace personnel.",
    "J'y reçois parfois des amis pour discuter."
  ],
  Salon: [
    "Le salon est la pièce principale de la maison.",
    "C'est là que nous recevons nos invités.",
    "Dans notre salon, il y a un grand canapé et deux fauteuils.",
    "Une table basse est placée devant le canapé.",
    "Sur la table basse, il y a souvent des magazines et des livres.",
    "Nous regardons la télévision dans le salon.",
    "Le soir, toute la famille se réunit dans le salon.",
    "Les enfants jouent parfois sur le tapis du salon.",
    "Notre salon est décoré avec beaucoup de soin.",
    "Les rideaux sont en tissu épais pour protéger de la lumière.",
    "Un grand miroir est accroché au mur.",
    "Des plantes vertes décorent les coins de la pièce.",
    "Le salon communique avec la salle à manger.",
    "Nous y écoutons de la musique le week-end."
  ],
  Habitation: [
    "Le lieu où on habite est un logement.",
    "On l'appelle aussi le domicile, par opposition avec le bureau ou le lieu où l'on travaille.",
    "En ville, les logements sont d'habitude des appartements.",
    "À la campagne ou dans les faubourgs, ce peut-être des maisons de plus d'un étage.",
    "Dans ce cas, la maison peut comporter une cave au sous-sol, un grenier sous le toit et des escaliers pour passer d'un étage à l'autre.",
    "Autour de la maison il peut y avoir un jardin.",
    "Un jardin où l'on cultive des légumes est appelé un potager.",
    "Un jardin où l'on cultive des fruits est appelé un verger.",
    "Dans chaque jardin il y a des fleurs plantées en pots ou dans le sol.",
    "Quelquefois des plantes grimpantes couvrent une partie de la façade.",
    "Les pelouses dans les jardins sont des surfaces plantées d'herbe verte que l'on coupe régulièrement.",
    "Les pelouses et les jardins demandent en général beaucoup de soin.",
    "Soigner un jardin exige beaucoup de temps et de patience.",
    "Tout le monde ne fait pas un bon jardinier.",
    "Les bons jardiniers sont plutôt rares.",
    "Une haie ou une clôture sépare en général une propriété d'une autre.",
    "Une propriété a une porte ou un portail qui donne sur la route.",
    "Les routes qui ne sont pas privées sont entretenues par la municipalité ou l'État.",
    "Les routes forment un réseau qui relie les divers lieux d'un pays.",
    "Un appartement est un ensemble de pièces dans un immeuble.",
    "Les immeubles peuvent avoir plusieurs étages.",
    "On prend l'escalier ou l'ascenseur pour monter.",
    "Chaque appartement a sa propre entrée.",
    "Le loyer est la somme que l'on paie chaque mois pour habiter un logement.",
    "Les propriétaires louent leurs biens à des locataires."
  ],
  Quartier: [
    "J'habite dans un quartier.",
    "Mon quartier est calme.",
    "Il y a une rue principale.",
    "La rue est large et animée.",
    "Il y a des trottoirs de chaque côté.",
    "Dans mon quartier, il y a des commerces.",
    "La boulangerie est au coin de la rue.",
    "L'épicerie est ouverte tous les jours.",
    "Il y a aussi une pharmacie et un café.",
    "Le café est souvent un lieu de rencontre pour les habitants.",
    "Les voisins se saluent parfois dans la rue.",
    "Les enfants jouent souvent dans le square.",
    "Le square est entouré d'arbres et de bancs.",
    "Une fontaine se trouve au centre du square.",
    "Quand il fait beau, les personnes âgées s'assoient sur les bancs.",
    "Le marché a lieu deux fois par semaine.",
    "On y trouve des fruits, des légumes et des fleurs.",
    "Les commerçants connaissent bien leurs clients.",
    "Quand il pleut, les rues se vident rapidement.",
    "Certaines rues sont piétonnes et interdites aux voitures.",
    "Le soir, les terrasses des cafés sont souvent très animées.",
    "Le quartier est desservi par plusieurs lignes de bus.",
    "La mairie se trouve à quelques minutes à pied.",
    "Parfois, des musiciens jouent dans la rue.",
    "Les immeubles anciens côtoient souvent les constructions modernes."
  ],
  "Grande surface": [
    "Les supermarchés font partie du paysage urbain.",
    "La plupart sont ouverts tous les jours.",
    "On y trouve de nombreux rayons.",
    "Les produits frais occupent souvent une grande partie du magasin.",
    "Le rayon des fruits et légumes propose des produits qui changent selon les saisons.",
    "Les produits laitiers se trouvent en général au fond du magasin.",
    "La viande et le poisson sont vendus dans des rayons spécialisés.",
    "Le pain et les viennoiseries sont préparés sur place dans certains magasins.",
    "Les conserves, les pâtes et le riz occupent les rayons centraux.",
    "Les produits surgelés sont rangés dans de grands congélateurs.",
    "À l'entrée, des chariots et des paniers sont mis à disposition des clients.",
    "Les prix sont indiqués sur les étiquettes fixées aux rayons.",
    "Certains produits sont régulièrement proposés en promotion.",
    "En général, les clients comparent les prix avant de choisir.",
    "À la caisse, on attend son tour dans la file.",
    "Le paiement se fait en espèces ou par carte bancaire.",
    "Certains magasins proposent des caisses en libre-service.",
    "Une carte de fidélité permet d'obtenir des réductions sur les achats.",
    "En général, les grandes surfaces disposent d'un vaste parking.",
    "Des places de stationnement sont réservées aux personnes handicapées.",
    "Les supermarchés sont souvent desservis par plusieurs lignes de bus.",
    "Des navettes relient parfois le magasin à la gare ou au centre-ville.",
    "Les grandes surfaces sont souvent construites en périphérie des villes.",
    "Elles attirent de nombreux clients venus de communes voisines.",
    "Certains supermarchés proposent aussi un service de livraison à domicile."
  ],
  "La ville": [
    "Les humains vivent souvent en groupes dans des lieux habités.",
    "Un petit lieu habité s'appelle un village.",
    "Une ville est plus grande qu'un village.",
    "Les villes varient beaucoup en taille et en population.",
    "Une métropole est une très grande ville qui rayonne sur toute une région.",
    "Chaque commune est administrée par une mairie.",
    "Le maire est élu par les habitants de la commune.",
    "Le conseil municipal prend les décisions importantes pour la vie locale.",
    "Les rues, les places et les parcs font partie de l'espace public.",
    "Les bâtiments publics comme les écoles et les hôpitaux sont accessibles à tous.",
    "En ville, les immeubles sont souvent construits les uns près des autres.",
    "Les transports en commun permettent de se déplacer sans voiture.",
    "Les grandes villes disposent en général de métros, de bus et de tramways.",
    "Les axes routiers relient les différents quartiers entre eux.",
    "Un boulevard est une large avenue bordée d'arbres.",
    "Les villes attirent de nombreuses personnes en quête de travail ou d'études.",
    "La population des villes a fortement augmenté au cours du vingtième siècle.",
    "Ce phénomène s'appelle l'urbanisation.",
    "L'urbanisation entraîne parfois des problèmes de logement et de circulation.",
    "Certaines villes cherchent à développer des espaces verts pour améliorer la qualité de vie.",
    "Les relations entre villes voisines sont souvent organisées en communautés d'agglomération.",
    "Une région regroupe plusieurs départements et dispose d'un conseil régional.",
    "Les grandes métropoles exercent une influence économique et culturelle sur les territoires qui les entourent.",
    "L'aménagement du territoire vise à répartir les activités et les populations de façon équilibrée.",
    "L'équilibre entre zones urbaines et zones rurales reste un enjeu majeur pour les sociétés contemporaines."
  ]
};

// ── Structure hiérarchique des thèmes englobants ──────────────────────────
// Permet la navigation à deux niveaux : thème englobant → sous-thème → phrases
// Les clés de DICTEES restent inchangées pour compatibilité avec le localStorage.

const THEMES_ENGLOBANTS = {
  "L'urbanisation": [
    "Maison",
    "Chambre",
    "Salon",
    "Habitation",
    "Quartier",
    "Grande surface",
    "La ville"
  ]
  // Futurs thèmes englobants à ajouter ici :
  // "Les études": ["L'école", "Le collège", "Le lycée", "L'université"],
  // "Les religions": ["Islam", "Christianisme", "Judaïsme", "La laïcité"],
};
