// data.js — Corpus des dictées (FLE/FLS — Nouvelles Dictées)
// Thème englobant : L'éducation
// Sous-thèmes : École primaire, Collège, Lycée, Université,
//               Formation professionnelle, Grandes écoles

const DICTEES = {
  "École primaire": [
    "L'école primaire accueille les enfants de six à onze ans.",
    "Elle comprend cinq niveaux : le CP, le CE1, le CE2, le CM1 et le CM2.",
    "Avant le CP, les enfants peuvent fréquenter l'école maternelle.",
    "L'école maternelle accueille les enfants à partir de trois ans.",
    "En France, l'instruction est obligatoire à partir de six ans.",
    "Chaque classe est encadrée par un enseignant ou une enseignante.",
    "Les élèves apprennent d'abord à lire, à écrire et à compter.",
    "Ces trois apprentissages fondamentaux sont la base de toute la scolarité.",
    "Les mathématiques et le français sont les deux matières principales.",
    "D'autres matières complètent l'enseignement : les sciences, l'histoire, la géographie et les arts.",
    "Les élèves ont aussi des cours d'éducation physique et sportive.",
    "La semaine scolaire est organisée en journées de classe et en récréations.",
    "Les récréations permettent aux élèves de se reposer et de jouer.",
    "Le cartable contient les cahiers, les livres et le matériel nécessaire au travail.",
    "Les enseignants évaluent régulièrement les progrès des élèves.",
    "Les parents sont informés des résultats lors des réunions ou par le carnet de correspondance.",
    "Certains élèves ont besoin d'un soutien particulier pour progresser.",
    "Des dispositifs d'aide existent pour les élèves en difficulté.",
    "La cantine scolaire permet aux élèves de déjeuner sur place.",
    "Certains élèves rentrent chez eux le midi, d'autres restent à l'école.",
    "Les vacances scolaires rythment l'année en plusieurs périodes.",
    "L'année scolaire commence en septembre et se termine en juin.",
    "À la fin du CM2, les élèves quittent l'école primaire pour entrer au collège.",
    "Le passage au collège représente une étape importante dans la scolarité.",
    "L'école primaire pose les fondations sur lesquelles s'appuie toute la formation future."
  ],
  "Collège": [
    "Le collège accueille les élèves de onze à quinze ans environ.",
    "Il comprend quatre niveaux : la sixième, la cinquième, la quatrième et la troisième.",
    "La sixième est la classe d'entrée au collège, après l'école primaire.",
    "Au collège, chaque matière est enseignée par un professeur différent.",
    "Les élèves changent de salle de classe selon les matières et les horaires.",
    "L'emploi du temps est organisé en heures de cours réparties sur la semaine.",
    "Les matières principales sont le français, les mathématiques, l'histoire-géographie et les langues vivantes.",
    "Les élèves commencent l'apprentissage d'une première langue étrangère dès la sixième.",
    "Une deuxième langue vivante est introduite en général à partir de la cinquième.",
    "Les sciences, la technologie, les arts et l'éducation physique complètent l'enseignement.",
    "Les professeurs évaluent les élèves par des devoirs, des interrogations et des contrôles.",
    "Les résultats sont consignés dans un bulletin scolaire remis aux familles chaque trimestre.",
    "Le conseil de classe réunit les professeurs et les délégués pour évaluer la progression des élèves.",
    "Les délégués de classe sont élus par les élèves pour les représenter.",
    "Certains élèves rencontrent des difficultés qui nécessitent un accompagnement particulier.",
    "Des heures de soutien et des dispositifs d'aide sont proposés au sein de l'établissement.",
    "La vie scolaire est encadrée par des conseillers principaux d'éducation.",
    "Le règlement intérieur définit les droits et les devoirs de chaque membre de la communauté scolaire.",
    "En troisième, les élèves effectuent un stage d'observation en entreprise.",
    "Ce stage permet de découvrir le monde professionnel et d'envisager des pistes d'orientation.",
    "À la fin de la troisième, les élèves passent le brevet des collèges.",
    "Le brevet évalue les connaissances acquises en français, en mathématiques et en histoire-géographie.",
    "Les résultats du brevet et les appréciations des professeurs orientent les élèves vers la suite de leur parcours.",
    "La plupart des élèves entrent au lycée général, technologique ou professionnel après le collège.",
    "Le collège est une période de transition entre les apprentissages fondamentaux et une formation plus spécialisée."
  ],
  "Lycée": [
    "Le lycée accueille les élèves de quinze à dix-huit ans environ.",
    "Il existe trois types de lycées : le lycée général, le lycée technologique et le lycée professionnel.",
    "Le lycée général prépare principalement aux études supérieures longues.",
    "Le lycée technologique propose des formations alliant enseignement général et technologique.",
    "Le lycée professionnel prépare les élèves à entrer directement dans la vie active.",
    "Le lycée comprend trois niveaux : la seconde, la première et la terminale.",
    "La classe de seconde est une année de découverte et d'orientation.",
    "En première, les élèves choisissent des spécialités en fonction de leurs projets.",
    "Ces spécialités déterminent en grande partie la direction des études supérieures.",
    "En terminale, les élèves approfondissent leurs spécialités et préparent le baccalauréat.",
    "Le baccalauréat est le diplôme qui sanctionne la fin des études secondaires.",
    "Il ouvre l'accès à l'enseignement supérieur et constitue le premier grade universitaire.",
    "Les épreuves du baccalauréat combinent des contrôles continus et des examens finaux.",
    "Parcoursup est la plateforme nationale qui organise l'entrée dans l'enseignement supérieur.",
    "Dès la classe de première, les élèves commencent à réfléchir à leur projet d'orientation.",
    "En terminale, ils formulent des vœux sur Parcoursup pour intégrer une formation après le bac.",
    "Chaque établissement examine les dossiers et formule une réponse à chaque candidat.",
    "Les élèves peuvent formuler jusqu'à dix vœux sur des formations très diverses.",
    "Parcoursup prend en compte les résultats scolaires, la lettre de motivation et le projet de l'élève.",
    "La procédure se déroule de janvier à juillet et mobilise fortement les élèves et les familles.",
    "Les lycéens bénéficient d'un accompagnement à l'orientation tout au long de leur scolarité.",
    "Des journées portes ouvertes dans les établissements supérieurs aident à construire ce projet.",
    "La vie lycéenne est aussi marquée par des engagements culturels, sportifs et associatifs.",
    "Le lycée développe l'autonomie et le sens des responsabilités des élèves.",
    "Il constitue une étape décisive entre l'enseignement obligatoire et l'entrée dans le supérieur."
  ],
  "Université": [
    "L'université est un établissement d'enseignement supérieur ouvert à tous les titulaires du baccalauréat.",
    "Elle propose des formations dans de nombreux domaines : droit, médecine, lettres, sciences, économie.",
    "Les études universitaires sont organisées en trois cycles principaux.",
    "Le premier cycle mène à la licence, obtenue après trois ans d'études.",
    "Le deuxième cycle mène au master, qui s'obtient en deux ans supplémentaires.",
    "Le troisième cycle conduit au doctorat, la plus haute qualification universitaire.",
    "Ce système est commun à la plupart des pays européens depuis la réforme dite LMD.",
    "Chaque université est divisée en unités de formation et de recherche appelées UFR.",
    "Les étudiants s'inscrivent dans une UFR selon leur domaine d'études.",
    "Les cours prennent la forme de cours magistraux et de travaux dirigés.",
    "Les cours magistraux réunissent un grand nombre d'étudiants dans un amphithéâtre.",
    "Les travaux dirigés se déroulent en petits groupes et favorisent les échanges.",
    "L'assiduité et l'autonomie sont des qualités indispensables pour réussir à l'université.",
    "Les étudiants doivent organiser eux-mêmes leur temps de travail en dehors des cours.",
    "Les bibliothèques universitaires offrent de nombreuses ressources pour approfondir les études.",
    "De nombreux étudiants travaillent à côté de leurs études pour financer leur vie quotidienne.",
    "Des bourses sur critères sociaux permettent d'aider les étudiants aux revenus modestes.",
    "Les résidences universitaires proposent des logements à des tarifs accessibles.",
    "La vie étudiante est animée par des associations culturelles, sportives et politiques.",
    "Certaines universités accueillent des étudiants étrangers dans le cadre de programmes d'échange.",
    "Le programme Erasmus permet aux étudiants européens de suivre une partie de leurs études à l'étranger.",
    "La recherche occupe une place centrale à l'université, notamment dans les cycles supérieurs.",
    "Les laboratoires de recherche sont souvent rattachés aux universités et aux grandes institutions scientifiques.",
    "Le diplôme universitaire est reconnu sur le marché du travail, mais son insertion dépend du domaine choisi.",
    "L'université forme des citoyens capables de pensée critique et d'analyse dans une société en constante évolution."
  ],
  "Formation professionnelle": [
    "La formation professionnelle prépare à l'exercice d'un métier précis.",
    "Elle s'adresse aussi bien aux jeunes qu'aux adultes en activité ou en recherche d'emploi.",
    "En France, la formation professionnelle est considérée comme un droit pour chaque travailleur.",
    "Elle peut prendre plusieurs formes : l'apprentissage, la formation continue ou la reconversion.",
    "L'apprentissage associe des périodes de formation en centre et des périodes de travail en entreprise.",
    "Ce système s'appelle l'alternance et permet d'acquérir une expérience professionnelle concrète.",
    "Les centres de formation des apprentis, appelés CFA, organisent la partie théorique de l'apprentissage.",
    "L'apprenti signe un contrat avec une entreprise qui s'engage à le former et à le rémunérer.",
    "Les diplômes préparés en apprentissage vont du CAP au master professionnel.",
    "Le CAP, certificat d'aptitude professionnelle, est le diplôme de base de l'enseignement professionnel.",
    "Le baccalauréat professionnel prépare à l'insertion directe dans la vie active ou à la poursuite d'études.",
    "Les brevets de technicien supérieur, appelés BTS, se préparent en deux ans après le baccalauréat.",
    "Les instituts universitaires de technologie, ou IUT, proposent des formations professionnalisantes de deux ans.",
    "Ces formations courtes sont très appréciées des employeurs pour leur dimension pratique.",
    "La formation continue permet aux salariés de développer de nouvelles compétences tout au long de leur carrière.",
    "Chaque salarié dispose d'un compte personnel de formation pour financer ses projets de développement.",
    "La reconversion professionnelle concerne les personnes qui souhaitent changer de métier.",
    "Elle peut être motivée par des raisons personnelles, économiques ou liées à l'évolution du marché du travail.",
    "Des organismes publics et privés proposent des formations adaptées à tous les profils et à tous les niveaux.",
    "Pôle emploi accompagne les demandeurs d'emploi dans leur recherche de formation et d'insertion.",
    "Certaines formations débouchent sur des certifications reconnues par les branches professionnelles.",
    "Les métiers de l'artisanat, du bâtiment, de la santé et des services recrutent régulièrement des personnes formées.",
    "La formation professionnelle joue un rôle essentiel dans la lutte contre le chômage et l'exclusion.",
    "Elle contribue à adapter les compétences des travailleurs aux évolutions technologiques et économiques.",
    "Dans une société en mutation, la capacité à se former tout au long de la vie devient une nécessité."
  ],
  "Grandes écoles": [
    "Les grandes écoles sont des établissements d'enseignement supérieur propres au système français.",
    "Elles se distinguent des universités par leur mode de recrutement sélectif sur concours.",
    "Les plus connues forment les ingénieurs, les managers et les hauts fonctionnaires de demain.",
    "L'accès aux grandes écoles passe en général par deux années de classes préparatoires.",
    "Les classes préparatoires, appelées familièrement prépas, sont rattachées à certains lycées.",
    "Elles exigent un travail intense et une grande capacité à absorber des connaissances variées.",
    "Les prépas scientifiques préparent aux écoles d'ingénieurs comme Polytechnique ou les Mines.",
    "Les prépas économiques et commerciales préparent aux écoles de commerce et de gestion.",
    "Les prépas littéraires préparent aux Écoles normales supérieures et à d'autres concours exigeants.",
    "À l'issue des prépas, les étudiants passent des concours communs très sélectifs.",
    "Le classement obtenu au concours détermine l'école intégrée et souvent la trajectoire professionnelle.",
    "Les grandes écoles d'ingénieurs forment des spécialistes capables de concevoir et de diriger des projets complexes.",
    "Les écoles de commerce forment des cadres pour les entreprises françaises et internationales.",
    "Les Écoles normales supérieures forment des chercheurs et des enseignants de haut niveau.",
    "L'École nationale d'administration, longtemps appelée ENA, formait les hauts fonctionnaires de l'État.",
    "Elle a été remplacée en 2022 par l'Institut national du service public, appelé INSP.",
    "Les grandes écoles entretiennent des réseaux d'anciens élèves très actifs dans la vie économique.",
    "Ces réseaux facilitent l'insertion professionnelle et jouent un rôle important dans les carrières.",
    "Le système des grandes écoles est souvent critiqué pour sa tendance à reproduire les élites sociales.",
    "Des dispositifs comme les internats d'excellence visent à ouvrir ces filières à des profils plus divers.",
    "Certaines grandes écoles ont développé des partenariats avec des universités étrangères de premier rang.",
    "La dimension internationale est devenue un critère important dans le classement de ces établissements.",
    "Les frais de scolarité varient considérablement selon les établissements et leur statut public ou privé.",
    "Les grandes écoles publiques sont souvent gratuites ou peu coûteuses grâce au financement de l'État.",
    "Le débat sur la place des grandes écoles dans le système éducatif français reste ouvert et vivace."
  ]
};

// ── Structure hiérarchique ────────────────────────────────────────────────
const THEMES_ENGLOBANTS = {
  "L'éducation": [
    "École primaire",
    "Collège",
    "Lycée",
    "Université",
    "Formation professionnelle",
    "Grandes écoles"
  ]
};
